# Build stage
FROM node:18-alpine AS build
WORKDIR /app

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


# Run stage
FROM nginx:alpine

# copy build output
COPY --from=build /app/dist /usr/share/nginx/html

# copy nginx config (QUAN TRỌNG)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
